[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "python manage.py migrate"
startCommand = "python -m http.server $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
