[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "python manage.py migrate"
startCommand = "gunicorn turnpiece.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 2 --log-level info"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
