[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "python manage.py migrate"
startCommand = "gunicorn turnpiece.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
